var photoPosts=new Array();

var photoPostsSource = [
    {
        id:'167438',         
        model:'эсминец',
        country:'Россия',
        displacement:'3500',
        price:'240.000.000',
        yearOfCreation:'1988',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Иванов Иван',
        photoLink:'https://static4.depositphotos.com/1000577/332/i/950/depositphotos_3329673-stock-photo-russian-warship-in-the-bay.jpg',
        createdAt: new Date('2018-02-23T23:00:00'),
        likes:new Array('Иванов Иван','Ветрова Юлия'),
        hashtags:new Array('#ThisIsPopular','#Ships','#MyGift')
    },
    {
        id:'777439',         
        model:'фрегат',
        country:'Украина',
        displacement:'1000',
        price:'300.000.000',
        yearOfCreation:'1950',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Ветрова Юлия',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Pantserkruiser_Aurora.jpg/300px-Pantserkruiser_Aurora.jpg',
        createdAt: new Date('2019-12-17T03:24:00'),
        likes:new Array('Юшкевич Олег'),
        hashtags:new Array('#ThisIsPopular')
    },
    {
        id:'345130',         
        model:'крейсер',
        country:'Америка',
        displacement:'5000',
        price:'1.000.000.000',
        yearOfCreation:'2000',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Иванов Иван',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Pallada_fregat.jpg/310px-Pallada_fregat.jpg',
        createdAt: new Date('2019-01-03T21:00:00'),
        likes:new Array('Ветрова Юлия'),
        hashtags:new Array('#Ships','#MyGift')
    },
    {
        id:'100921',         
        model:'крейсер',
        country:'Великобритания',
        displacement:'4500',
        price:'1.200.000.000',
        yearOfCreation:'2010',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Юшкевич Олег',
        photoLink:'https://topwar.ru/uploads/posts/2018-03/1521375433_gvardeyskiy-raketnyy-kreyser-4913.jpg',
        createdAt: new Date('2019-11-15T08:13:00'),
        likes:new Array('Ветрова Юлия'),
        hashtags:new Array('#MyShip','#Ships')
    },
    {
        id:'923900',         
        model:'миноносец',
        country:'Испания',
        displacement:'2000',
        price:'200.000.000',
        yearOfCreation:'1979',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Зубович Валера',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/3/38/Rastoropnyy%26O%27Bannon1992.jpg',
        createdAt: new Date('2020-05-06T10:25:00'),
        likes:new Array('Ветрова Юлия','Юшкевич Олег'),
        hashtags:new Array('#MyShip')
    },
    {
        id:'178126',         
        model:'десантный корабль',
        country:'Португалия',
        displacement:'3000',
        price:'800.000.000',
        yearOfCreation:'2015',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Щавель Илья',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KostiantynOl%27shans%27kyi2010Tendra.jpg/300px-KostiantynOl%27shans%27kyi2010Tendra.jpg',
        createdAt: new Date('2021-01-26T14:30:00'),
        likes:new Array('Масюк Павел','Юшкевич Олег'),
        hashtags:new Array('#MyShip','#MyGift')
    },
    {
        id:'008126',         
        model:'десантный корабль',
        country:'Португалия',
        displacement:'2800',
        price:'700.000.000',
        yearOfCreation:'2014',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Масюк Павел',
        photoLink:'https://vpk.name/file/img/bdk_oslyabya_tof_provel_artilleriiskie_strelbyi_i_vyisadil_desant_na_neoborudovannoe_poberezhe-txq573gq-1521714512.jpg',
        createdAt: new Date('2021-01-26T14:30:00'),
        likes:new Array('Щавель Илья','Юшкевич Олег'),
        hashtags:new Array('#MyShip',"#Product")
    },
    {
        id:'905126',         
        model:'авианосец',
        country:'Бразилия',
        displacement:'3800',
        price:'700.000.000',
        yearOfCreation:'2013',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Щавель Илья',
        photoLink:'https://cdn2.img.inosmi.ru/images/24896/20/248962027.jpg',
        createdAt: new Date('2021-01-26T19:45:00'),
        likes:new Array('Ветрова Юлия','Зубович Валера','Щавель Илья'),
        hashtags:new Array('#Ships','#MyGift')
    },
    {
        id:'330127',         
        model:'авианосец',
        country:'Нигерия',
        displacement:'4000',
        price:'900.000.000',
        yearOfCreation:'2013',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Масюк Павел',
        photoLink:'https://topwar.ru/uploads/posts/2019-10/1570799499_w22-1.jpg',
        createdAt: new Date('2011-06-13T10:47:00'),
        likes:new Array('Иванов Иван','Ветрова Юлия'),
        hashtags:new Array('#ThisIsPopular','#Ships','#MyGift')
    },
    {
        id:'207438',         
        model:'эсминец',
        country:'Россия',
        displacement:'1500',
        price:'200.000.000',
        yearOfCreation:'1908',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Иванов Иван',
        photoLink:'https://warspot-asset.s3.amazonaws.com/articles/announces/000/007/807/source/1-7d24a8b7b5578638051648fb6a472062.jpg',
        createdAt: new Date('2001-01-03T03:00:00'),
        likes:new Array('Иванов Иван','Ветрова Юлия'),
        hashtags:new Array('#ThisIsPopular','#Ships','#Product')
    },
    {
        id:'657439',         
        model:'фрегат',
        country:'Украина',
        displacement:'3000',
        price:'150.000.000',
        yearOfCreation:'1950',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Ветрова Юлия',
        photoLink:'https://s.rfi.fr/media/display/7be3aa74-0f31-11ea-b61a-005056a9aa4d/w:1280/p:16x9/000_par8246500.webp',
        createdAt: new Date('2019-10-07T01:25:00'),
        likes:new Array('Щавель Илья','Масюк Павел'),
        hashtags:new Array('#ThisIsPopular','#Ships','#MyGift')
    },
    {
        id:'345130',         
        model:'крейсер',
        country:'Америка',
        displacement:'5000',
        price:'1.000.000.000',
        yearOfCreation:'2000',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Иванов Иван',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Pallada_fregat.jpg/310px-Pallada_fregat.jpg',
        createdAt: new Date('2019-01-03T21:00:00'),
        likes:new Array('Ветрова Юлия'),
        hashtags:new Array('#Ships','#Product')
    },
    {
        id:'110921',         
        model:'крейсер',
        country:'Америка',
        displacement:'4500',
        price:'1.200.000.000',
        yearOfCreation:'2010',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Юшкевич Олег',
        photoLink:'https://cdn1.img.inosmi.ru/images/24301/38/243013878.jpg',
        createdAt: new Date('2019-11-15T08:00:00'),
        likes:new Array('Ветрова Юлия','Иванов Иван','Зубович Валера'),
        hashtags:new Array('#Product','#ThisIsPopular','#Ships')
    },
    {
        id:'903900',         
        model:'миноносец',
        country:'Испания',
        displacement:'2000',
        price:'200.000.000',
        yearOfCreation:'1979',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Зубович Валера',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/7/73/%C2%AB%D0%90%D0%B4%D0%BC%D0%B8%D1%80%D0%B0%D0%BB_%D0%A3%D1%88%D0%B0%D0%BA%D0%BE%D0%B2%C2%BB.jpg',
        createdAt: new Date('2003-05-06T10:25:00'),
        likes:new Array('Масюк Павел','Пупкин Вася','Щавель Илья'),
        hashtags:new Array('#Product','#ThisIsPopular','#Ships')
    },
    {
        id:'188126',         
        model:'десантный корабль',
        country:'Португалия',
        displacement:'3000',
        price:'800.000.000',
        yearOfCreation:'2015',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Щавель Илья',
        photoLink:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KostiantynOl%27shans%27kyi2010Tendra.jpg/300px-KostiantynOl%27shans%27kyi2010Tendra.jpg',
        createdAt: new Date('2005-01-26T14:30:00'),
        likes:new Array('Пупкин Вася','Иванов Иван','Зубович Валера'),
        hashtags:new Array('#Ships')
    },
    {
        id:'118126',         
        model:'десантный корабль',
        country:'Россия',
        displacement:'2800',
        price:'700.000.000',
        yearOfCreation:'2014',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Масюк Павел',
        photoLink:'https://cdnimg.rg.ru/img/content/201/50/44/nevar1000_d_850.jpg',
        createdAt: new Date('2011-03-26T14:30:00'),
        likes:new Array('Ветрова Юлия','Иванов Иван','Зубович Валера'),
        hashtags:new Array('#Ships')
    },
    {
        id:'945126',         
        model:'авианосец',
        country:'Бразилия',
        displacement:'3800',
        price:'700.000.000',
        yearOfCreation:'2013',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Щавель Илья',
        photoLink:'https://cdn2.img.inosmi.ru/images/24896/20/248962027.jpg',
        createdAt: new Date('2000-01-26T19:45:00'),
        likes:new Array('Ветрова Юлия','Иванов Иван','Зубович Валера'),
        hashtags:new Array('#Ships','#MyGift','#MyShip','#Product')
    },
    {
        id:'100127',         
        model:'авианосец',
        country:'Нигерия',
        displacement:'4000',
        price:'900.000.000',
        yearOfCreation:'2013',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Масюк Павел',
        photoLink:'https://cdn.profile.ru/wp-content/uploads/2020/01/proekt-avianosca-CVN-81.jpg',
        createdAt: new Date('2013-12-13T01:47:00'),
        likes:new Array('Юшкевич Олег','Зубович Валера','Пупкин Вася','Масюк Павел'),
        hashtags:new Array('#ThisIsPopular','#Ships')
    },
    {
        id:'945000',         
        model:'корвет',
        country:'Италия',
        displacement:'1800',
        price:'150.000.000',
        yearOfCreation:'2009',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Пупкин Вася',
        photoLink:'https://cdnimg.rg.ru/img/content/173/47/09/222_d_850.jpg',
        createdAt: new Date('2010-01-26T19:15:00'),
        likes:new Array('Щавель Илья','Масюк Павел','Пупкин Вася'),
        hashtags:new Array('#ThisIsPopular','#Ships')
    },
    {
        id:'100007',         
        model:'корвет',
        country:'Нигерия',
        displacement:'8000',
        price:'700.000.000',
        yearOfCreation:'1999',
        description:'хорошо укомплектован, рассчитат на большую команду, не требует спец проверки',
        author:'Пупкин Вася',
        photoLink:'http://military-informant.com/wp-content/uploads/2011/02/milgem.jpg',
        createdAt: new Date('2013-12-13T01:47:00'),
        likes:new Array('Щавель Илья','Масюк Павел','Пупкин Вася'),
        hashtags:new Array('#ThisIsPopular','#Ships')
    }
];
           
var ArrOfHashtags=['#ThisIsPopular','#Ships','#MyGift','#MyShip','#Product'];
var ArrOfNames=['Иванов Иван','Ветрова Юлия','Юшкевич Олег','Зубович Валера','Щавель Илья','Масюк Павел','Пупкин Вася'];
var ArrOfModels=['эсминец','корвет','авианосец','десантный корабль','миноносец','крейсер'];
